name: expense_manager_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # NOTE: necessary
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # NOTE: State Management
  flutter_bloc: ^8.1.3
  # NOTE: Database
  sqflite: ^2.2.8+4
  path: ^1.8.3
  # NOTE: Datetime Formatting
  intl: ^0.18.1
  # NOTE: API
  http: ^1.1.0
  # NOTE: Improve development process
  dartz: ^0.10.1
  # NOTE: Others
  uuid: ^3.0.7
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9
  math_expressions: ^2.4.0
  flutter_native_splash: ^2.3.3

flutter_native_splash:
  image: assets/images/start_page.png
  color: "#006783"
  android_disable_fullscreen: true
  android_12:
    image: assets/images/start_page.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/start_page.png
